name: Docker

on:
  push:
    # Publish `name` branches as tags
    branches:
      - "*"
      - "!master"

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$VERSION

          docker build . --file Dockerfile.$VERSION --tag $IMAGE_ID:latest

      - name: Log into registry
        run: echo "${{ secrets.GPR_AUTH_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$VERSION

          docker push "$IMAGE_ID:latest"
