name: Docker

on:
  push:
    # Publish `name` branches as tags
    branches:
      - "*"
      - "!master"

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo VERSION=$VERSION

          docker build . --file Dockerfile.$VERSION --tag image

      - name: Log into registry
        run: echo "${{ secrets.GPR_AUTH_TOKEN }}" | docker login docker.pkg.github.com -u k-deployer --password-stdin

      - name: Push image
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$VERSION

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
